### ISSUE TITLE
Furnaces fuel indicator sometimes stuck when using Lava bucket

### ISSUE THREAD

**Issue by vico93** [XenoMustache/ironfurnaces#1]
Hi! I began to get a stuck fuel indicator in IF furnaces in some cases:

First, like i reported [here](https://github.com/Tschipp/CarryOn/issues/132), using CarryOn's carry feature on a furnace which got a lava bucket as fuel sometimes stuck when i put the furnace back.
Second, one time i place a lava bucket as fuel, as soon it was consumed (and the fuel indicator started to tick) i need to teleport me to a far place (so the chunk where the furnace was placed was unloaded), when i was back the fuel was stuck.

These were the two moments i got this bug, is this somewhat intended (lava bucket lasting far more than vanilla furnaces)? Coal and other fuels last the same.

Anyway thanks for this mod!

**Comment by XenoMustache** [comment]
Reproducing these actions yields no erroneous behavior from the furnaces. I will look into it in the code side of things, but in the meantime I recommend keeping the furnaces loaded with a chunk loader from Chicken Chunks or FTB Utilities.

**Comment by vico93** [comment]
I will try to nail down a way to reproduce this. If i can i will reopen the issue.
I currently  use [Persistent bits](https://minecraft.curseforge.com/projects/persistent-bits) as chunk loader, i will give it a try. Thanks!

**Comment by XenoMustache** [comment]
I was able to successfully reproduce the issue. It seems that lava buckets do last far longer than intended. I will look into fixing this issue.

**Comment by XenoMustache** [comment]
Upon closer inspection, it seems that the fuel indicator is simply not updating properly as time passes. Eventually it will fix itself however and quickly run out, meaning that this is just a graphical bug. Nevertheless I am looking into fixing it.

**Comment by vico93** [comment]
Ok thanks Xeno! Will look forward a fix!
